_logging_pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5level} log_level=\"%level\" ${PID:- } --- [thread=\"%thread\", httpMethod=\"%X{httpMethod:-null}\", httpRequestURI=\"%X{httpRequestURI:-null}\", X-Request-ID=\"%X{requestId:-null}\"] [%15.15t] %-40.40logger{39} : %replace(%msg){'\r\n|\n', '\u2028'} %replace(%ex{full}){'\r\n|\n', '\u2028'}%nopex"
_logging_pattern_console: "${_logging_pattern}%n"
logging:
  pattern:
    console: ${_logging_pattern_console}

jwt:
  publicKey: ${PUBLIC_KEY}
  privateKey: ${PRIVATE_KEY}
  audience: "localhost:3000"
cloudflare:
  api:
    accountID: ${CLOUDFLARE_ACCOUNTID}
    key: ${CLOUDFLARE_KEY}
server:
  port: 5455
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DEV_USERNAME}
    password: ${MYSQL_DEV_USER_PASSWORD}
    url: jdbc:mysql://mysql-dev:3306/${MYSQL_DEV_DATABASE}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq-dev
    username: ${RABBITMQ_DEV_USERNAME}
    password: ${RABBITMQ_DEV_PASSWORD}
    port: 61613
    requested-heartbeat: 580
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

app:
  environment:
    ALLOWED_ORIGINS:
      - ${ALLOWED_ORIGIN}